apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: ack-rds-ctrl.kro.run
  namespace: kro
spec:
  schema:
    apiVersion: v1alpha1
    kind: Rdscontroller
    spec:
      name: string | default=${schema.spec.name}
      namespace: string | default=${schema.spec.namespace}
      values:
        aws:
          accountID: string | default=${schema.spec.aws.accountID}
          credentials:
            profile: string | default=${schema.spec.aws.credentials.profile}
            secretKey: string | default=${schema.spec.aws.credentials.secretKey}
            secretName: string | default=${schema.spec.aws.credentials.secretName}
          region: string | default=${schema.spec.aws.region}
        deletionPolicy: string | default=delete
        deployment:
          affinity: object | default={}
          annotations: object | default={}
          containerPort: integer | default=8080
          dnsPolicy: string | default=ClusterFirst
          extraEnvVars: object | default={}
          extraVolumeMounts: object | default={}
          extraVolumes: object | default={}
          hostNetwork: boolean | default=false
          labels: object | default={}
          nodeSelector: object | default={"kubernetes.io/os":"linux"}
          priorityClassName: string | default=""
          replicas: integer | default=1
          strategy: object | default={}
          tolerations: object | default={}
        enableCARM: boolean | default=true
        featureGates: object | default={"ServiceLevelCARM":false,"TeamLevelCARM":false,"ReadOnlyResources":true,"ResourceAdoption":true}
        iamRole:
          maxSessionDuration: integer | default=3600
          oidcProvider: string | default=""
          roleDescription: string | default=IRSA role for ACK rds controller deployment on EKS cluster using KRO Resource Graph
        image:
          pullPolicy: string | default=IfNotPresent
          pullSecrets: string[] | default=[]
          repository: string | default=${schema.spec.image.repository}
          tag: string | default=${schema.spec.image.tag}
        installScope: string | default=cluster
        leaderElection:
          enabled: boolean | default=false
          namespace: string | default=${schema.spec.namespace}
        log:
          enable_development_logging: boolean | default=false
          level: string | default=${schema.spec.log.level}
        metrics:
          service:
            create: boolean | default=true
            type: string | default=ClusterIP
        reconcile:
          defaultMaxConcurrentSyncs: integer | default=5
          defaultResyncPeriod: string | default=10h
          resourceMaxConcurrentSyncs: object | default={}
          resourceResyncPeriods: object | default={}
          resources: string[] | default=[]
        resourceTags: string[] | default=["services.k8s.aws/controller-version=${schema.spec.name}-${schema.spec.image.tag}","services.k8s.aws/namespace=${schema.spec.namespace}"]
        resources:
          limits:
            cpu: string | default=100m
            memory: string | default=128Mi
          requests:
            cpu: string | default=50m
            memory: string | default=64Mi
        role:
          labels: object | default={}
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: ${schema.spec.serviceAccount.annotations["eks.amazonaws.com/role-arn"]}
          create: boolean | default=true
          name: string | default=${schema.spec.serviceAccount.name}
        watchNamespace: string | default=${schema.spec.watchNamespace}
        watchSelectors: string | default=""
  resources:
    - id: graph-rds-crds
      template:
        apiVersion: kro.run/v1alpha1
        kind: Rdscrdgraph
        metadata:
          name: ${schema.spec.name}-crd-graph
        spec:
          name: ${schema.spec.name}-crd-graph
    - id: graph-serviceaccount
      template:
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          annotations:
            eks.amazonaws.com/role-arn: ${schema.spec.serviceAccount.annotations["eks.amazonaws.com/role-arn"]}
          labels:
            app.kubernetes.io/instance: __KRO${schema.spec.name}_
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: rds-chart
            app.kubernetes.io/version: 1.6.2
            helm.sh/chart: rds-chart-1.6.2
            k8s-app: rds-chart
          name: ${schema.spec.serviceAccount.name}
          namespace: __KRO${schema.spec.namespace}_
    - id: graph-clusterrole
      template:
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRole
        metadata:
          labels:
            app.kubernetes.io/instance: __KRO${schema.spec.name}_
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: rds-chart
            app.kubernetes.io/version: 1.6.2
            helm.sh/chart: rds-chart-1.6.2
            k8s-app: rds-chart
          name: __KRO${schema.spec.name}_-rds-chart
        rules:
          - apiGroups:
              - ""
            resources:
              - configmaps
              - secrets
            verbs:
              - get
              - list
              - patch
              - watch
          - apiGroups:
              - ""
            resources:
              - namespaces
            verbs:
              - get
              - list
              - watch
          - apiGroups:
              - ec2.services.k8s.aws
            resources:
              - securitygroups
              - securitygroups/status
              - subnets
              - subnets/status
            verbs:
              - get
              - list
          - apiGroups:
              - kms.services.k8s.aws
            resources:
              - keys
              - keys/status
            verbs:
              - get
              - list
          - apiGroups:
              - rds.services.k8s.aws
            resources:
              - dbclusterendpoints
              - dbclusterparametergroups
              - dbclusters
              - dbclustersnapshots
              - dbinstances
              - dbparametergroups
              - dbproxies
              - dbsnapshots
              - dbsubnetgroups
              - globalclusters
            verbs:
              - create
              - delete
              - get
              - list
              - patch
              - update
              - watch
          - apiGroups:
              - rds.services.k8s.aws
            resources:
              - dbclusterendpoints/status
              - dbclusterparametergroups/status
              - dbclusters/status
              - dbclustersnapshots/status
              - dbinstances/status
              - dbparametergroups/status
              - dbproxies/status
              - dbsnapshots/status
              - dbsubnetgroups/status
              - globalclusters/status
            verbs:
              - get
              - patch
              - update
          - apiGroups:
              - services.k8s.aws
            resources:
              - adoptedresources
              - fieldexports
            verbs:
              - create
              - delete
              - get
              - list
              - patch
              - update
              - watch
          - apiGroups:
              - services.k8s.aws
            resources:
              - adoptedresources/status
              - fieldexports/status
            verbs:
              - get
              - patch
              - update
    - id: graph-clusterrole-2
      template:
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRole
        metadata:
          labels:
            app.kubernetes.io/instance: __KRO${schema.spec.name}_
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: rds-chart
            app.kubernetes.io/version: 1.6.2
            helm.sh/chart: rds-chart-1.6.2
            k8s-app: rds-chart
          name: __KRO${schema.spec.name}_-rds-chart-namespaces-cache
        rules:
          - apiGroups:
              - ""
            resources:
              - namespaces
            verbs:
              - get
              - list
              - watch
    - id: graph-clusterrolebinding
      template:
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          labels:
            app.kubernetes.io/instance: __KRO${schema.spec.name}_
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: rds-chart
            app.kubernetes.io/version: 1.6.2
            helm.sh/chart: rds-chart-1.6.2
            k8s-app: rds-chart
          name: __KRO${schema.spec.name}_-rds-chart-namespaces-cache
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: __KRO${schema.spec.name}_-rds-chart-namespaces-cache
        subjects:
          - kind: ServiceAccount
            name: ${schema.spec.serviceAccount.name}
            namespace: __KRO${schema.spec.namespace}_
    - id: graph-clusterrolebinding-2
      template:
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          labels:
            app.kubernetes.io/instance: __KRO${schema.spec.name}_
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: rds-chart
            app.kubernetes.io/version: 1.6.2
            helm.sh/chart: rds-chart-1.6.2
            k8s-app: rds-chart
          name: __KRO${schema.spec.name}_-rds-chart-rolebinding
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: __KRO${schema.spec.name}_-rds-chart
        subjects:
          - kind: ServiceAccount
            name: ${schema.spec.serviceAccount.name}
            namespace: __KRO${schema.spec.namespace}_
    - id: graph-role
      template:
        apiVersion: rbac.authorization.k8s.io/v1
        kind: Role
        metadata:
          labels:
            app.kubernetes.io/instance: __KRO${schema.spec.name}_
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: rds-chart
            app.kubernetes.io/version: 1.6.2
            helm.sh/chart: rds-chart-1.6.2
            k8s-app: rds-chart
          name: __KRO${schema.spec.name}_-rds-chart-configmaps-cache
          namespace: __KRO${schema.spec.namespace}_
        rules:
          - apiGroups:
              - ""
            resources:
              - configmaps
            verbs:
              - get
              - list
              - watch
    - id: graph-role-2
      template:
        apiVersion: rbac.authorization.k8s.io/v1
        kind: Role
        metadata:
          creationTimestamp: null
          labels:
            app.kubernetes.io/instance: __KRO${schema.spec.name}_
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: rds-chart
            app.kubernetes.io/version: 1.6.2
            helm.sh/chart: rds-chart-1.6.2
            k8s-app: rds-chart
          name: __KRO${schema.spec.name}_-rds-chart-reader
          namespace: __KRO${schema.spec.namespace}_
        rules:
          - apiGroups:
              - rds.services.k8s.aws
            resources:
              - dbclusters
              - dbclusterendpoints
              - dbclusterparametergroups
              - dbclustersnapshots
              - dbinstances
              - dbparametergroups
              - dbproxies
              - dbsnapshots
              - dbsubnetgroups
              - globalclusters
            verbs:
              - get
              - list
              - watch
    - id: graph-role-3
      template:
        apiVersion: rbac.authorization.k8s.io/v1
        kind: Role
        metadata:
          creationTimestamp: null
          labels:
            app.kubernetes.io/instance: __KRO${schema.spec.name}_
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: rds-chart
            app.kubernetes.io/version: 1.6.2
            helm.sh/chart: rds-chart-1.6.2
            k8s-app: rds-chart
          name: __KRO${schema.spec.name}_-rds-chart-writer
          namespace: __KRO${schema.spec.namespace}_
        rules:
          - apiGroups:
              - rds.services.k8s.aws
            resources:
              - dbclusters
              - dbclusterendpoints
              - dbclusterparametergroups
              - dbclustersnapshots
              - dbinstances
              - dbparametergroups
              - dbproxies
              - dbsnapshots
              - dbsubnetgroups
              - globalclusters
            verbs:
              - create
              - delete
              - get
              - list
              - patch
              - update
              - watch
          - apiGroups:
              - rds.services.k8s.aws
            resources:
              - dbclusters
              - dbclusterendpoints
              - dbclusterparametergroups
              - dbclustersnapshots
              - dbinstances
              - dbparametergroups
              - dbproxies
              - dbsnapshots
              - dbsubnetgroups
              - globalclusters
            verbs:
              - get
              - patch
              - update
    - id: graph-rolebinding
      template:
        apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
          labels:
            app.kubernetes.io/instance: __KRO${schema.spec.name}_
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: rds-chart
            app.kubernetes.io/version: 1.6.2
            helm.sh/chart: rds-chart-1.6.2
            k8s-app: rds-chart
          name: __KRO${schema.spec.name}_-rds-chart-configmaps-cache
          namespace: __KRO${schema.spec.namespace}_
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: Role
          name: __KRO${schema.spec.name}_-rds-chart-configmaps-cache
        subjects:
          - kind: ServiceAccount
            name: ${schema.spec.serviceAccount.name}
            namespace: __KRO${schema.spec.namespace}_
    - id: graph-deployment
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          labels:
            app.kubernetes.io/instance: __KRO${schema.spec.name}_
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: rds-chart
            app.kubernetes.io/version: 1.6.2
            helm.sh/chart: rds-chart-1.6.2
            k8s-app: rds-chart
          name: __KRO${schema.spec.name}_-rds-chart
          namespace: __KRO${schema.spec.namespace}_
        spec:
          replicas: 1
          selector:
            matchLabels:
              app.kubernetes.io/instance: __KRO${schema.spec.name}_
              app.kubernetes.io/name: rds-chart
          template:
            metadata:
              labels:
                app.kubernetes.io/instance: __KRO${schema.spec.name}_
                app.kubernetes.io/managed-by: Helm
                app.kubernetes.io/name: rds-chart
                k8s-app: rds-chart
            spec:
              containers:
                - args:
                    - --aws-region
                    - $(AWS_REGION)
                    - --aws-endpoint-url
                    - $(AWS_ENDPOINT_URL)
                    - --log-level
                    - $(ACK_LOG_LEVEL)
                    - --resource-tags
                    - $(ACK_RESOURCE_TAGS)
                    - --watch-namespace
                    - $(ACK_WATCH_NAMESPACE)
                    - --watch-selectors
                    - $(ACK_WATCH_SELECTORS)
                    - --reconcile-resources
                    - $(RECONCILE_RESOURCES)
                    - --deletion-policy
                    - $(DELETION_POLICY)
                    - --reconcile-default-resync-seconds
                    - $(RECONCILE_DEFAULT_RESYNC_SECONDS)
                    - --reconcile-default-max-concurrent-syncs
                    - $(RECONCILE_DEFAULT_MAX_CONCURRENT_SYNCS)
                    - --feature-gates
                    - $(FEATURE_GATES)
                    - --enable-carm=true
                  command:
                    - ./bin/controller
                  env:
                    - name: ACK_SYSTEM_NAMESPACE
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.namespace
                    - name: AWS_REGION
                      value: ${schema.spec.aws.region}
                    - name: AWS_ENDPOINT_URL
                      value: ""
                    - name: ACK_WATCH_NAMESPACE
                      value: null
                    - name: ACK_WATCH_SELECTORS
                      value: null
                    - name: RECONCILE_RESOURCES
                      value: DBCluster,DBClusterEndpoint,DBClusterParameterGroup,DBClusterSnapshot,DBInstance,DBParameterGroup,DBProxy,DBSnapshot,DBSubnetGroup,GlobalCluster
                    - name: DELETION_POLICY
                      value: delete
                    - name: LEADER_ELECTION_NAMESPACE
                      value: ""
                    - name: ACK_LOG_LEVEL
                      value: info
                    - name: ACK_RESOURCE_TAGS
                      value: services.k8s.aws/controller-version=%CONTROLLER_SERVICE%-%CONTROLLER_VERSION%,services.k8s.aws/namespace=%K8S_NAMESPACE%
                    - name: RECONCILE_DEFAULT_RESYNC_SECONDS
                      value: "36000"
                    - name: RECONCILE_DEFAULT_MAX_CONCURRENT_SYNCS
                      value: "1"
                    - name: FEATURE_GATES
                      value: ReadOnlyResources=true,ResourceAdoption=true,ServiceLevelCARM=false,TeamLevelCARM=false
                  image: ${schema.spec.image.repository}:${schema.spec.image.tag}
                  imagePullPolicy: IfNotPresent
                  livenessProbe:
                    httpGet:
                      path: /healthz
                      port: 8081
                    initialDelaySeconds: 15
                    periodSeconds: 20
                  name: controller
                  ports:
                    - containerPort: 8080
                      name: http
                  readinessProbe:
                    httpGet:
                      path: /readyz
                      port: 8081
                    initialDelaySeconds: 5
                    periodSeconds: 10
                  resources:
                    limits:
                      cpu: 100m
                      memory: 128Mi
                    requests:
                      cpu: 50m
                      memory: 64Mi
                  securityContext:
                    allowPrivilegeEscalation: false
                    capabilities:
                      drop:
                        - ALL
                    privileged: false
                    readOnlyRootFilesystem: true
                    runAsNonRoot: true
              dnsPolicy: ClusterFirst
              hostIPC: false
              hostNetwork: false
              hostPID: false
              nodeSelector:
                kubernetes.io/os: linux
              securityContext:
                seccompProfile:
                  type: RuntimeDefault
              serviceAccountName: ${schema.spec.serviceAccount.name}
              terminationGracePeriodSeconds: 10
